# Only apply in deploy previews
[context.deploy-preview]
  [[redirects]]
    from = "/assests/test-preview.css"
    to = "/404.html"
    status = 404

[[redirects]]
  from = "/assets/index-*.css"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"